'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/component/navbar/navbar";
import Footer from "@/app/component/footer/footer";
import { Provider } from "react-redux";
import store from "@/lib/store/store";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname=usePathname()
  const noNavbarRoutes = ["/admin/dashboard", "/admin/dashboard/category","/admin/dashboard/reservation","/admin/dashboard/menu","/admin/dashboard/table","/admin/dashboard/users"]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
        <div className="flex flex-col min-h-screen">
          {!noNavbarRoutes.includes(pathname) && <Navbar />}
        <main className="flex-grow">
            {children}
          </main>
        {!noNavbarRoutes.includes(pathname) && <Footer />}
        </div>
        </Provider>
      </body>
    </html>
  );
}
